#!/usr/bin/env bash

# 参数部分  -----------------------------------------------------------------------------------------------------------------
stage=3
stop_stage=3
export CUDA_VISIBLE_DEVICES=1

: ${embedding_layers:="1,7"}      # 若未定义则默认0 ~ 7
: ${num_codebooks:="16,16"}     # 若未定义则默认2,4,8,16
IFS=',' read -ra embedding_layer <<< "$embedding_layers"  # 分割字符串到数组
IFS=',' read -ra num_codebook <<< "$num_codebooks"
exp_dir=./QUAD/exp
mkdir -p $exp_dir

. shared/parse_options.sh || exit 1
log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}
if [ ! -d ./data/fbank ]; then
  log "This script assumes ./data/fbank is already generated by prepare.sh"
  exit 1
fi

# 提取码本索引部分 ----------------------------------------------------------------------------------------------------------
if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then

  # --num-utts-extracted 360294   part 360182
  # --embedding-dim layer7:(256 s    512 m    768 l)   layer1: 192

  use_extracted_codebook=False
  export MODEL_TYPE="zipformer_l_56"
  teacher_model_id=zipformer_l_56

  ./QUAD/extract_codebook_index.py \
    --kd-exp-dir $exp_dir \
    --embedding-layer ${embedding_layer[0]} \
    --num-utts 2000 \
    --num-codebooks ${num_codebook[0]} \
    --max-duration 300 \
    --teacher-model-id $teacher_model_id \
    --spec-aug-time-warp-factor -1 \
    --embedding-dim 192 \
    --num-utts-extracted 360294 \
    --use-extracted-codebook $use_extracted_codebook

  ./QUAD/extract_codebook_index.py \
    --kd-exp-dir $exp_dir \
    --embedding-layer ${embedding_layer[1]} \
    --num-utts 2000 \
    --num-codebooks ${num_codebook[1]} \
    --max-duration 300 \
    --teacher-model-id $teacher_model_id \
    --spec-aug-time-warp-factor -1 \
    --embedding-dim 768 \
    --num-utts-extracted 360294 \
    --use-extracted-codebook $use_extracted_codebook

  # export MODEL_TYPE="zipformer_m_55"
  # teacher_model_id=zipformer_m_55

  # ./QUAD/extract_codebook_index.py \
  #   --kd-exp-dir $exp_dir \
  #   --embedding-layer ${embedding_layer[0]} \
  #   --num-utts 2000 \
  #   --num-codebooks ${num_codebook[0]} \
  #   --max-duration 300 \
  #   --teacher-model-id $teacher_model_id \
  #   --spec-aug-time-warp-factor -1 \
  #   --embedding-dim 192 \
  #   --num-utts-extracted 360294 \
  #   --use-extracted-codebook $use_extracted_codebook

  # ./QUAD/extract_codebook_index.py \
  #   --kd-exp-dir $exp_dir \
  #   --embedding-layer ${embedding_layer[1]} \
  #   --num-utts 2000 \
  #   --num-codebooks ${num_codebook[1]} \
  #   --max-duration 300 \
  #   --teacher-model-id $teacher_model_id \
  #   --spec-aug-time-warp-factor -1 \
  #   --embedding-dim 512 \
  #   --num-utts-extracted 360294 \
  #   --use-extracted-codebook $use_extracted_codebook

  # export MODEL_TYPE="zipformer_s_55"
  # teacher_model_id=zipformer_s_55

  # ./QUAD/extract_codebook_index.py \
  #   --kd-exp-dir $exp_dir \
  #   --embedding-layer ${embedding_layer[0]} \
  #   --num-utts 2000 \
  #   --num-codebooks ${num_codebook[0]} \
  #   --max-duration 300 \
  #   --teacher-model-id $teacher_model_id \
  #   --spec-aug-time-warp-factor -1 \
  #   --embedding-dim 192 \
  #   --num-utts-extracted 360294 \
  #   --use-extracted-codebook $use_extracted_codebook

  # ./QUAD/extract_codebook_index.py \
  #   --kd-exp-dir $exp_dir \
  #   --embedding-layer ${embedding_layer[1]} \
  #   --num-utts 2000 \
  #   --num-codebooks ${num_codebook[1]} \
  #   --max-duration 300 \
  #   --teacher-model-id $teacher_model_id \
  #   --spec-aug-time-warp-factor -1 \
  #   --embedding-dim 256 \
  #   --num-utts-extracted 360294 \
  #   --use-extracted-codebook $use_extracted_codebook

fi

# 聚合多层码本索引部分----------------------------------------------------------------------------------------------------------
if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
    # part 1: combine single teacher layers CI        part 2: combine multiple teacher's CI

  # teacher_model_id=zipformer_l_56
  # use_mul_tea=False

  # ./QUAD/combine_jsonl.py \
  #   --output-path $exp_dir \
  #   --teacher-model-id $teacher_model_id \
  #   --use-mul-tea $use_mul_tea

  # teacher_model_id=zipformer_m_55
  # use_mul_tea=False

  # ./QUAD/combine_jsonl.py \
  #   --output-path $exp_dir \
  #   --teacher-model-id $teacher_model_id \
  #   --use-mul-tea $use_mul_tea

  # teacher_model_id=zipformer_s_55
  # use_mul_tea=False

  # ./QUAD/combine_jsonl.py \
  #   --output-path $exp_dir \
  #   --teacher-model-id $teacher_model_id \
  #   --use-mul-tea $use_mul_tea

  use_mul_tea=True

  ./QUAD/combine_jsonl.py \
    --output-path $exp_dir \
    --use-mul-tea $use_mul_tea

fi

# 训练学生模型部分----------------------------------------------------------------------------------------------------------
if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  # Example training script.
  # Note: it's better to set spec-aug-time-warpi-factor=-1
  WORLD_SIZE=$(echo ${CUDA_VISIBLE_DEVICES} | awk '{n=split($1, _, ","); print n}')
  # --manifest-dir $exp_dir/${embedding_layer}_cb${num_codebooks} \
  # --exp-dir $exp_dir/student/multilayer_${embedding_layer[0]}_${embedding_layer[1]}_cb${num_codebook[0]}_
  # --exp-dir $exp_dir/student/zipformer_xs_squeeze/fraction15/mtml

  use_mul_tea=True

  ./QUAD/train_xs_new.py \
    --manifest-dir $exp_dir/combined_${embedding_layer[0]}_${embedding_layer[1]} \
    --spec-aug-time-warp-factor -1 \
    --max-duration 300 \
    --world-size ${WORLD_SIZE} \
    --num-epochs 60 \
    --start-epoch 1 \
    --save-every-n 100000 \
    --exp-dir $exp_dir/student/xs_full_dataset/lsmvq-ml \
    --distillation-layer $embedding_layers \
    --num-codebooks $num_codebooks \
    --enable-distillation True \
    --enable-multilayer-distillation True \
    --use-mul-tea $use_mul_tea \
    --codebook-loss-scale 0.1 \
    --layers-weight-opt "avg" \
    --tea-weight-opt "test-m" \
    --data-fraction 1

  ./QUAD/train_xs_new.py \
    --manifest-dir $exp_dir/combined_${embedding_layer[0]}_${embedding_layer[1]} \
    --spec-aug-time-warp-factor -1 \
    --max-duration 300 \
    --world-size ${WORLD_SIZE} \
    --num-epochs 70 \
    --start-epoch 51 \
    --save-every-n 100000 \
    --exp-dir $exp_dir/student/xs_full_dataset/lsmvq-ml \
    --distillation-layer $embedding_layers \
    --num-codebooks $num_codebooks \
    --enable-distillation False \
    --enable-multilayer-distillation True \
    --use-mul-tea $use_mul_tea \
    --codebook-loss-scale 0.1 \
    --layers-weight-opt "avg" \
   --tea-weight-opt "test-m" \
    --data-fraction 1 \
    --early-stop True

fi

# 解码学生模型部分----------------------------------------------------------------------------------------------------------
if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  # Results should be similar to:
  # errs-test-clean-beam_size_4-epoch-20-avg-10-beam-4.txt:%WER = 5.67
  # errs-test-other-beam_size_4-epoch-20-avg-10-beam-4.txt:%WER = 15.60
  ./QUAD/decode_xs.py \
    --decoding-method "greedy_search" \
    --epoch 70 \
    --avg 17 \
    --max-duration 750 \
    --exp-dir $exp_dir/student/xs_full_dataset/lsmvq-ml \
    --lang-dir data/lang_char \
    --context-size 1 \
    --distillation-layer $embedding_layers \
    --num-codebooks $num_codebooks \
    --layers-weight-opt "avg" \
    --enable-distillation True \
    --use-averaged-model True

  # ./QUAD/decode_m.py \
  #   --decoding-method "greedy_search" \
  #   --epoch 55 \
  #   --avg 1 \
  #   --max-duration 750 \
  #   --exp-dir $exp_dir/teachers/zipformer-m \
  #   --lang-dir data/lang_char \
  #   --context-size 1 \
  #   --enable-distillation False \
  #   --use-averaged-model False

fi

